name: CMake

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Check out branch
      uses: actions/checkout@v3

    - name: Install Google Test
      run: |
        sudo apt-get install -y libgtest-dev

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./calculatorclionpridemic_test
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

    - name: Build Docker Image
      if: success()
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: projectdatics/calculatorpridemic:${{ github.sha }}
        builder: docker

