name: CMake

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Check out branch
      uses: actions/checkout@v3

    - name: Install Google Test
      run: |
        sudo apt-get install libgtest-dev
        sudo apt-get install cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make 
    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./calculatorclionpridemic_test

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: calculatorclionpridemic
        path: calculatorclionpridemic
    - name: Build Docker image
      run: docker build -t projectdatics/calculatorclionpridemic:latest .
    - name: Push Docker image
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - run: docker push projectdatics/calculatorclionpridemic:latest

